### ISSUE TITLE
換黨執政切分點顏色變化

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/draw#3]
現在換黨執政都切在2000,2008,2016年，但其實想想他們也是五月才上任，有可能在這個**_資料點_**上以雙色呈現（如2016是左藍右綠）嗎？monthly-visitors的 2016/5 一樣～

**Comment by chihhhhhao** [comment]
dc3b24109bcb881a5ae6ce94f4f44d75dc6d9095 加入執政黨色彩背景

**Comment by chihhhhhao** [comment]
e59b7f066efc87d34927a68367e1a58c5cbbafa1 加入總統姓名
