### ISSUE TITLE
圖表次序變更

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/draw#5]
現在我們的不然你來畫畫看總共有七張圖，為讓故事說起來更有趣，希望改成以下順序

1.每年失業率
2.每年來台旅客
3.每月來台中國旅客
4.每月來台世界旅客
5.各年度中央政府歲入
6.各年度中央政府歲出
7.各年度中央政府一年以上債務

**Comment by chihhhhhao** [comment]
修改`tsai-first-year/src/data/graphs.js`裡面graph object在array裡的順序就可以變更圖表在網頁上呈現的順序囉！要挑戰看看嗎？

**Comment by chihhhhhao** [comment]
178f2213f1adc308116bcfdcff55f0ac322f1ab2
